//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administradore
    {
        public int id_admin { get; set; }
        public string usuario { get; set; }
        public string email { get; set; }
        public string password_hash { get; set; }
        public string nombre_completo { get; set; }
        public string rol { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> ultimo_acceso { get; set; }
    }
}
