//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVs_Egresados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CVs_Egresados()
        {
            this.Matching_Resultados = new HashSet<Matching_Resultados>();
            this.Procesos_Seleccion = new HashSet<Procesos_Seleccion>();
        }
    
        public int id_cv { get; set; }
        public int id_egresado { get; set; }
        public string ruta_archivo { get; set; }
        public string nombre_archivo { get; set; }
        public Nullable<long> tamaño_archivo { get; set; }
        public Nullable<decimal> experiencia_años { get; set; }
        public string habilidades_principales { get; set; }
        public string idiomas { get; set; }
        public string certificaciones { get; set; }
        public Nullable<bool> disponible_busqueda { get; set; }
        public Nullable<System.DateTime> fecha_subida { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public Nullable<int> veces_visualizado { get; set; }
    
        public virtual Egresado Egresado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matching_Resultados> Matching_Resultados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Procesos_Seleccion> Procesos_Seleccion { get; set; }
    }
}
