//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoEgresados.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SistemaEgresadosUtecEntities : DbContext
    {
        public SistemaEgresadosUtecEntities()
            : base("name=SistemaEgresadosUtecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administradore> Administradores { get; set; }
        public virtual DbSet<Carrera> Carreras { get; set; }
        public virtual DbSet<CVs_Egresados> CVs_Egresados { get; set; }
        public virtual DbSet<Egresado> Egresados { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<Encuestas_Base> Encuestas_Base { get; set; }
        public virtual DbSet<Estrellas_Egresado> Estrellas_Egresado { get; set; }
        public virtual DbSet<Evaluaciones_Proceso> Evaluaciones_Proceso { get; set; }
        public virtual DbSet<Logs_Sistema> Logs_Sistema { get; set; }
        public virtual DbSet<Matching_Config> Matching_Config { get; set; }
        public virtual DbSet<Matching_Resultados> Matching_Resultados { get; set; }
        public virtual DbSet<Notificacione> Notificaciones { get; set; }
        public virtual DbSet<Procesos_Seleccion> Procesos_Seleccion { get; set; }
        public virtual DbSet<Usuarios_Empresa> Usuarios_Empresa { get; set; }
        public virtual DbSet<VW_Dashboard_Egresados> VW_Dashboard_Egresados { get; set; }
        public virtual DbSet<VW_Estadisticas_Empresas> VW_Estadisticas_Empresas { get; set; }
    
        public virtual int SP_CalcularMatching(Nullable<int> id_empresa, Nullable<int> top_candidates)
        {
            var id_empresaParameter = id_empresa.HasValue ?
                new ObjectParameter("id_empresa", id_empresa) :
                new ObjectParameter("id_empresa", typeof(int));
    
            var top_candidatesParameter = top_candidates.HasValue ?
                new ObjectParameter("top_candidates", top_candidates) :
                new ObjectParameter("top_candidates", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CalcularMatching", id_empresaParameter, top_candidatesParameter);
        }
    
        public virtual int SP_ArchivarMentoria(Nullable<int> id_mentoria, string usuario_tipo, Nullable<int> id_usuario, string ip_address)
        {
            var id_mentoriaParameter = id_mentoria.HasValue ?
                new ObjectParameter("id_mentoria", id_mentoria) :
                new ObjectParameter("id_mentoria", typeof(int));
    
            var usuario_tipoParameter = usuario_tipo != null ?
                new ObjectParameter("usuario_tipo", usuario_tipo) :
                new ObjectParameter("usuario_tipo", typeof(string));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var ip_addressParameter = ip_address != null ?
                new ObjectParameter("ip_address", ip_address) :
                new ObjectParameter("ip_address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ArchivarMentoria", id_mentoriaParameter, usuario_tipoParameter, id_usuarioParameter, ip_addressParameter);
        }
    
        public virtual int SP_ArchivarSesionMentoria(Nullable<int> id_sesion, string usuario_tipo, Nullable<int> id_usuario, string ip_address)
        {
            var id_sesionParameter = id_sesion.HasValue ?
                new ObjectParameter("id_sesion", id_sesion) :
                new ObjectParameter("id_sesion", typeof(int));
    
            var usuario_tipoParameter = usuario_tipo != null ?
                new ObjectParameter("usuario_tipo", usuario_tipo) :
                new ObjectParameter("usuario_tipo", typeof(string));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var ip_addressParameter = ip_address != null ?
                new ObjectParameter("ip_address", ip_address) :
                new ObjectParameter("ip_address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ArchivarSesionMentoria", id_sesionParameter, usuario_tipoParameter, id_usuarioParameter, ip_addressParameter);
        }
    
        public virtual int SP_EliminarMentoria(Nullable<int> id_mentoria, string usuario_tipo, Nullable<int> id_usuario, string ip_address)
        {
            var id_mentoriaParameter = id_mentoria.HasValue ?
                new ObjectParameter("id_mentoria", id_mentoria) :
                new ObjectParameter("id_mentoria", typeof(int));
    
            var usuario_tipoParameter = usuario_tipo != null ?
                new ObjectParameter("usuario_tipo", usuario_tipo) :
                new ObjectParameter("usuario_tipo", typeof(string));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var ip_addressParameter = ip_address != null ?
                new ObjectParameter("ip_address", ip_address) :
                new ObjectParameter("ip_address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarMentoria", id_mentoriaParameter, usuario_tipoParameter, id_usuarioParameter, ip_addressParameter);
        }
    
        public virtual int SP_EliminarSesionMentoria(Nullable<int> id_sesion, string usuario_tipo, Nullable<int> id_usuario, string ip_address)
        {
            var id_sesionParameter = id_sesion.HasValue ?
                new ObjectParameter("id_sesion", id_sesion) :
                new ObjectParameter("id_sesion", typeof(int));
    
            var usuario_tipoParameter = usuario_tipo != null ?
                new ObjectParameter("usuario_tipo", usuario_tipo) :
                new ObjectParameter("usuario_tipo", typeof(string));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var ip_addressParameter = ip_address != null ?
                new ObjectParameter("ip_address", ip_address) :
                new ObjectParameter("ip_address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarSesionMentoria", id_sesionParameter, usuario_tipoParameter, id_usuarioParameter, ip_addressParameter);
        }
    
        public virtual int SP_LimpiarSesionesHuerfanas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LimpiarSesionesHuerfanas");
        }
    
        public virtual int SP_LogAccionSistema(string usuario_tipo, Nullable<int> id_usuario, string accion, string tabla_afectada, Nullable<int> id_registro, string detalles, string ip_address)
        {
            var usuario_tipoParameter = usuario_tipo != null ?
                new ObjectParameter("usuario_tipo", usuario_tipo) :
                new ObjectParameter("usuario_tipo", typeof(string));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var accionParameter = accion != null ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(string));
    
            var tabla_afectadaParameter = tabla_afectada != null ?
                new ObjectParameter("tabla_afectada", tabla_afectada) :
                new ObjectParameter("tabla_afectada", typeof(string));
    
            var id_registroParameter = id_registro.HasValue ?
                new ObjectParameter("id_registro", id_registro) :
                new ObjectParameter("id_registro", typeof(int));
    
            var detallesParameter = detalles != null ?
                new ObjectParameter("detalles", detalles) :
                new ObjectParameter("detalles", typeof(string));
    
            var ip_addressParameter = ip_address != null ?
                new ObjectParameter("ip_address", ip_address) :
                new ObjectParameter("ip_address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LogAccionSistema", usuario_tipoParameter, id_usuarioParameter, accionParameter, tabla_afectadaParameter, id_registroParameter, detallesParameter, ip_addressParameter);
        }
    }
}
