//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egresado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Egresado()
        {
            this.CVs_Egresados = new HashSet<CVs_Egresados>();
            this.Encuestas_Base = new HashSet<Encuestas_Base>();
            this.Estrellas_Egresado = new HashSet<Estrellas_Egresado>();
            this.Matching_Resultados = new HashSet<Matching_Resultados>();
            this.Mentorias = new HashSet<Mentoria>();
            this.Mentorias1 = new HashSet<Mentoria>();
            this.Procesos_Seleccion = new HashSet<Procesos_Seleccion>();
        }
    
        public int id_egresado { get; set; }
        public string numero_documento { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public int id_carrera { get; set; }
        public System.DateTime fecha_graduacion { get; set; }
        public Nullable<decimal> promedio_academico { get; set; }
        public Nullable<bool> consentimiento_datos { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<bool> estado_activo { get; set; }
        public Nullable<decimal> puntuacion_global { get; set; }
        public Nullable<int> total_estrellas { get; set; }
        public string nivel_experiencia { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CVs_Egresados> CVs_Egresados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encuestas_Base> Encuestas_Base { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estrellas_Egresado> Estrellas_Egresado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matching_Resultados> Matching_Resultados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mentoria> Mentorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mentoria> Mentorias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Procesos_Seleccion> Procesos_Seleccion { get; set; }
    }
}
