//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoEgresados.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SistemaEgresadosUtecEntities : DbContext
    {
        public SistemaEgresadosUtecEntities()
            : base("name=SistemaEgresadosUtecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administradore> Administradores { get; set; }
        public virtual DbSet<Carrera> Carreras { get; set; }
        public virtual DbSet<CVs_Egresados> CVs_Egresados { get; set; }
        public virtual DbSet<Egresado> Egresados { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<Encuestas_Base> Encuestas_Base { get; set; }
        public virtual DbSet<Estrellas_Egresado> Estrellas_Egresado { get; set; }
        public virtual DbSet<Evaluaciones_Proceso> Evaluaciones_Proceso { get; set; }
        public virtual DbSet<Logs_Sistema> Logs_Sistema { get; set; }
        public virtual DbSet<Matching_Config> Matching_Config { get; set; }
        public virtual DbSet<Matching_Resultados> Matching_Resultados { get; set; }
        public virtual DbSet<Notificacione> Notificaciones { get; set; }
        public virtual DbSet<Procesos_Seleccion> Procesos_Seleccion { get; set; }
        public virtual DbSet<Usuarios_Empresa> Usuarios_Empresa { get; set; }
        public virtual DbSet<VW_Dashboard_Egresados> VW_Dashboard_Egresados { get; set; }
        public virtual DbSet<VW_Estadisticas_Empresas> VW_Estadisticas_Empresas { get; set; }
        public virtual DbSet<Mentoria> Mentorias { get; set; }
        public virtual DbSet<Sesiones_Mentoria> Sesiones_Mentoria { get; set; }
    
        public virtual int SP_CalcularMatching(Nullable<int> id_empresa, Nullable<int> top_candidates)
        {
            var id_empresaParameter = id_empresa.HasValue ?
                new ObjectParameter("id_empresa", id_empresa) :
                new ObjectParameter("id_empresa", typeof(int));
    
            var top_candidatesParameter = top_candidates.HasValue ?
                new ObjectParameter("top_candidates", top_candidates) :
                new ObjectParameter("top_candidates", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CalcularMatching", id_empresaParameter, top_candidatesParameter);
        }
    }
}
