//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Matching_Config = new HashSet<Matching_Config>();
            this.Matching_Resultados = new HashSet<Matching_Resultados>();
            this.Procesos_Seleccion = new HashSet<Procesos_Seleccion>();
            this.Usuarios_Empresa = new HashSet<Usuarios_Empresa>();
        }
    
        public int id_empresa { get; set; }
        public string razon_social { get; set; }
        public string nit { get; set; }
        public string email_contacto { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string sector_economico { get; set; }
        public string tamaño_empresa { get; set; }
        public Nullable<bool> vinculada_universidad { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<bool> estado_activo { get; set; }
        public Nullable<decimal> puntuacion_empresa { get; set; }
        public Nullable<int> total_contrataciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matching_Config> Matching_Config { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matching_Resultados> Matching_Resultados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Procesos_Seleccion> Procesos_Seleccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios_Empresa> Usuarios_Empresa { get; set; }
    }
}
