//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encuestas_Base
    {
        public int id_encuesta { get; set; }
        public int id_egresado { get; set; }
        public bool trabajando_actualmente { get; set; }
        public string empresa_actual { get; set; }
        public string cargo_actual { get; set; }
        public string salario_rango { get; set; }
        public string modalidad_trabajo { get; set; }
        public Nullable<byte> satisfaccion_trabajo { get; set; }
        public Nullable<bool> usa_conocimientos_carrera { get; set; }
        public Nullable<int> tiempo_conseguir_trabajo { get; set; }
        public Nullable<System.DateTime> fecha_encuesta { get; set; }
        public string contacta_universidad { get; set; }
        public Nullable<byte> desea_contacto { get; set; }
        public Nullable<byte> dispuesto_encuesta_semestral { get; set; }
        public string metodo_inicio_sesion { get; set; }
        public string respuestas_json { get; set; }
        public string sugerencia_funcionalidad { get; set; }
    
        public virtual Egresado Egresado { get; set; }
    }
}
