//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estrellas_Egresado
    {
        public int id_estrella { get; set; }
        public int id_egresado { get; set; }
        public int id_proceso { get; set; }
        public int estrella_numero { get; set; }
        public Nullable<bool> completada { get; set; }
        public Nullable<decimal> puntuacion_obtenida { get; set; }
        public Nullable<System.DateTime> fecha_obtencion { get; set; }
        public string fase_completada { get; set; }
    
        public virtual Egresado Egresado { get; set; }
        public virtual Procesos_Seleccion Procesos_Seleccion { get; set; }
    }
}
