//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluaciones_Proceso
    {
        public int id_evaluacion { get; set; }
        public int id_proceso { get; set; }
        public string fase_evaluacion { get; set; }
        public decimal puntuacion { get; set; }
        public Nullable<decimal> puntuacion_maxima { get; set; }
        public string comentarios { get; set; }
        public string evaluador { get; set; }
        public Nullable<System.DateTime> fecha_evaluacion { get; set; }
        public Nullable<bool> completada { get; set; }
    
        public virtual Procesos_Seleccion Procesos_Seleccion { get; set; }
    }
}
