//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matching_Resultados
    {
        public int id_matching { get; set; }
        public int id_empresa { get; set; }
        public int id_egresado { get; set; }
        public int id_cv { get; set; }
        public decimal puntuacion_match { get; set; }
        public string desglose_puntuacion { get; set; }
        public Nullable<System.DateTime> fecha_calculo { get; set; }
        public Nullable<bool> visualizado_empresa { get; set; }
        public Nullable<System.DateTime> fecha_visualizacion { get; set; }
    
        public virtual CVs_Egresados CVs_Egresados { get; set; }
        public virtual Egresado Egresado { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
