//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matching_Config
    {
        public int id_config { get; set; }
        public int id_empresa { get; set; }
        public Nullable<decimal> peso_experiencia { get; set; }
        public Nullable<decimal> peso_habilidades { get; set; }
        public Nullable<decimal> peso_calificaciones { get; set; }
        public Nullable<decimal> peso_carrera { get; set; }
        public Nullable<decimal> peso_idiomas { get; set; }
        public Nullable<int> experiencia_minima { get; set; }
        public string carreras_preferidas { get; set; }
        public string habilidades_requeridas { get; set; }
        public Nullable<System.DateTime> fecha_configuracion { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
