//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mentoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mentoria()
        {
            this.Sesiones_Mentoria = new HashSet<Sesiones_Mentoria>();
        }
    
        public int id_mentoria { get; set; }
        public Nullable<int> id_mentor { get; set; }
        public Nullable<int> id_mentee { get; set; }
        public string estado_mentoria { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_finalizacion { get; set; }
        public string area_mentoria { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public string objetivos { get; set; }
        public string progreso { get; set; }
        public Nullable<int> calificacion_mentor { get; set; }
        public Nullable<int> calificacion_mentee { get; set; }
        public string comentarios_finales { get; set; }
    
        public virtual Egresado Egresado { get; set; }
        public virtual Egresado Egresado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sesiones_Mentoria> Sesiones_Mentoria { get; set; }
    }
}
