//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procesos_Seleccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Procesos_Seleccion()
        {
            this.Estrellas_Egresado = new HashSet<Estrellas_Egresado>();
            this.Evaluaciones_Proceso = new HashSet<Evaluaciones_Proceso>();
        }
    
        public int id_proceso { get; set; }
        public int id_empresa { get; set; }
        public int id_egresado { get; set; }
        public int id_cv { get; set; }
        public string titulo_vacante { get; set; }
        public string descripcion_vacante { get; set; }
        public Nullable<decimal> salario_ofrecido { get; set; }
        public string modalidad { get; set; }
        public string estado_proceso { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public Nullable<System.DateTime> fecha_finalizacion { get; set; }
        public Nullable<bool> contratado { get; set; }
        public string observaciones { get; set; }
    
        public virtual CVs_Egresados CVs_Egresados { get; set; }
        public virtual Egresado Egresado { get; set; }
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estrellas_Egresado> Estrellas_Egresado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluaciones_Proceso> Evaluaciones_Proceso { get; set; }
    }
}
