//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sesiones_Mentoria
    {
        public int id_sesion { get; set; }
        public int id_mentoria { get; set; }
        public System.DateTime fecha_sesion { get; set; }
        public Nullable<int> duracion_minutos { get; set; }
        public string modalidad { get; set; }
        public string temas_tratados { get; set; }
        public string proximos_pasos { get; set; }
        public Nullable<int> calificacion_sesion { get; set; }
        public Nullable<bool> completada { get; set; }
    
        public virtual Mentoria Mentoria { get; set; }
    }
}
