//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios_Empresa
    {
        public int id_usuario { get; set; }
        public int id_empresa { get; set; }
        public string nombre_usuario { get; set; }
        public string email { get; set; }
        public string password_hash { get; set; }
        public string nombre_completo { get; set; }
        public string cargo { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
