//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Dashboard_Egresados
    {
        public int id_egresado { get; set; }
        public string nombre_completo { get; set; }
        public string email { get; set; }
        public string nombre_carrera { get; set; }
        public string facultad { get; set; }
        public System.DateTime fecha_graduacion { get; set; }
        public Nullable<int> meses_desde_graduacion { get; set; }
        public Nullable<decimal> puntuacion_global { get; set; }
        public Nullable<int> total_estrellas { get; set; }
        public string nivel_experiencia { get; set; }
        public string estado_laboral { get; set; }
        public Nullable<int> total_aplicaciones { get; set; }
        public Nullable<int> total_contrataciones { get; set; }
    }
}
