//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Estadisticas_Empresas
    {
        public int id_empresa { get; set; }
        public string razon_social { get; set; }
        public string sector_economico { get; set; }
        public Nullable<decimal> puntuacion_empresa { get; set; }
        public Nullable<int> total_candidatos_evaluados { get; set; }
        public Nullable<int> total_contrataciones { get; set; }
        public Nullable<decimal> promedio_evaluacion_cv { get; set; }
        public Nullable<decimal> promedio_evaluacion_tecnica { get; set; }
    }
}
